### ISSUE TITLE
Changes to Chrome TextBaseline coming

### ISSUE THREAD

**Issue by willbamford** [mapbox/tiny-sdf#11]
Hi, just a heads up that Chrome's interpretation of text baseline has just changed to match FF i.e. what was filed as a [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=737852) is actually inline with the spec, and Chrome have [dropped in a fix](https://bugs.chromium.org/p/chromium/issues/detail?id=607053) to align to this.

So the line at https://github.com/mapbox/tiny-sdf/blob/master/index.js#L34 may not work with a future Chrome release.

**Comment by mourner** [comment]
@WebSeed Thank you for letting us know! So we should probably change that to:

```js
this.middle = Math.round(1.2 * size / 2);
```

Right? Also, do you have an idea of when this fix will hit the stable channel and in what Chrome version?

**Comment by WebSeed** [comment]
I'm guessing changing to `1.2 * size / 2` would then result in weirdness in IE / Safari. Not sure when it'll land in Chrome release - I just happened to stumble on the FF bug page today and it mentioned Chrome had merged the change in.

TBH I'm not sure what solution to consistency is. Perhaps default `alphabetic` alignment is more consistent across browsers? But then of course you'd need to adjust where text was drawn vertically to accommodate this.
