### ISSUE TITLE
Difference between tiny-sdf and node-fontnik?

### ISSUE THREAD

**Issue by shayke** [mapbox/tiny-sdf#14]
I've tried playing with the demo here using `Open Sans` font at 24px:
![image](https://user-images.githubusercontent.com/1285887/57180518-f0285880-6e91-11e9-8c26-db5e8dbab324.png)

The 'S' letter rendered on mapbox looks like that:
![image](https://user-images.githubusercontent.com/1285887/57180508-beaf8d00-6e91-11e9-84fa-f0bca93b787a.png)

Why there are such big differences of the letter smoothing?
Mapbox (using pbf fonts) is using node-fontnik behind the scenes no?
I've tried playing with the gamma in the demo but nothing get's as sharp as it looks in mapbox.

Thanks!

**Comment by mourner** [comment]
Sorry for not responding in time. The key difference is that `node-fontnik` generates SDFs from vector server-side, so it needs smaller resolution for a crisper rendering, while `tiny-sdf` works client-side and generates SDF from raster image, which is inherently lower quality, but allows doing this on the browser side — the original goal of this library was to avoid expensive font server requests in the CJK area (China, Japan, South Korea etc.). Increasing resolution is the main way to make the rendering sharper — see https://github.com/mapbox/mapbox-gl-js/pull/10298
