### ISSUE TITLE
Render "Halfwidth and Fullwidth Forms" unicode block

### ISSUE THREAD

**Issue by kkaefer** [mapbox/tiny-sdf#20]
The "Halfwidth and Fullwidth Forms" block contains versions of latin characters that are adjusted to be used in a CJK monospaced environment. Since we can guess the width of these glyphs, we can render them with TinySDF, unlike their proportional equivalents.

**Comment by mourner** [comment]
#24 enables rendering CJK mixed with Latin characters, so I think that PR supercedes the issue here, right?
