### ISSUE TITLE
Potential optimization: ignore buffer when running EDT on the inner grid

### ISSUE THREAD

**Issue by mourner** [mapbox/tiny-sdf#32]
Currently we run the distance transform on both the outer grid and the inner grid on the whole canvas:

```js
edt(gridOuter, width, height, this.f, this.v, this.z);
edt(gridInner, width, height, this.f, this.v, this.z);
```

The inner grid should only contain meaningful data inside the actual bounding box of the glyph — buffer regions are filled with zeroes, so in theory we could make the EDT part of tiny-sdf faster by only running it on the bbox for the inner grid rather than the whole canvas.

Since EDT is linear time, for default values (fontSize = 24, buffer = 3) the speedup should roughly be (30^2 - 24^2) / (2 * 30^2) = 18%.

cc @ChrisLoer

**Comment by ChrisLoer** [comment]
That would be a solid improvement, and useful in the c++ version as well. I'm not sure I understand the algorithm well enough, though -- I thought it was possible that even though that area is initialized to 0 the edt could set it to non-zero?

**Comment by mourner** [comment]
@ChrisLoer since every pixel signifies distance to the closest "drawn" pixel, pixels that are already "drawn" (initialized as 0) always remain zero — which is the case for area outside the glyph for the inner grid, since we generate it to track distances to inside the drawn area.
