### ISSUE TITLE
getting an error in example code

### ISSUE THREAD

**Issue by opheliagame** [mapbox/tiny-sdf#36]
`tiny-sdf.js:84 
Uncaught TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.
at TinySDF._draw (tiny-sdf.js:84)
at TinySDF.draw (tiny-sdf.js:105)`

I am getting this error while trying to run the example code and I'm not sure what I am doing wrong. Any help would be really wonderful.

**Comment by mourner** [comment]
Can you set up a live test page to reproduce this? Does the published demo at https://mapbox.github.io/tiny-sdf/ show the same error for you?

**Comment by opheliagame** [comment]
[jsfiddle](https://jsfiddle.net/41Lgayjc/)
the demo link does not give any error and I feel like I am doing a beginner mistake, so I'm sorry if I am wasting some time.

**Comment by mourner** [comment]
Oh, sorry, this is absolutely not your mistake — looks like we accidentally updated the readme example with the new API, even though it's in a version not yet released! In the meantime, here's the readme for the released version: https://github.com/mapbox/tiny-sdf/blob/v1.2.5/README.md

**Comment by mourner** [comment]
v2 released!
