### ISSUE TITLE
Cropped last row

### ISSUE THREAD

**Issue by boris-ulyanov** [mapbox/tiny-sdf#42]
Hi!

I noticed that bottom row of the bitmap is cropped for all characters:

![original](https://user-images.githubusercontent.com/5022380/147727479-2fb95b35-1151-41e1-a879-010229a08128.png)

Did not understand where the error, but if increase `glyphHeight` by one on line https://github.com/mapbox/tiny-sdf/blob/main/index.js#L59 :

![fixed](https://user-images.githubusercontent.com/5022380/147728527-b48269f4-1c3c-4c01-b577-3fb6624fc205.png)

Checked on chrome/firefox windows/linux/android

**Comment by mourner** [comment]
I thought this was already fixed by https://github.com/mapbox/tiny-sdf/pull/33, are you sure this is reproducible with the latest version of TinySDF? I don't see it clipped on the current demo: https://mapbox.github.io/tiny-sdf/

**Comment by boris-ulyanov** [comment]
Strange, right now I see this on the demo page (on default params):

![demo2](https://user-images.githubusercontent.com/5022380/147807632-3d2b4598-1661-424b-b956-486851f8494a.png)

Same result reproduced local on latest version

**Comment by mourner** [comment]
Fixed by #43?
