### ISSUE TITLE
How to improve the performance of getImageData, it takes too long

### ISSUE THREAD

**Issue by xiaoch11** [mapbox/tiny-sdf#46]

**Comment by ryanhamley** [comment]
Hi @xiaoch11 I'm not sure what specific issue you're having. GL JS doesn't have a `getImageData` method. However, if you're having an issue with animating images, we did just [fix a performance regression](https://github.com/mapbox/mapbox-gl-js/pull/11564) with that and it will be released as part of v2.8.0 in the next few days. Thanks.
