### ISSUE TITLE
Some weird behavior when using with pnpm

### ISSUE THREAD

**Issue by digoburigo** [mapbox/tiny-sdf#49]
When I clear the pnpm store cache with `pnpm store prune` and the project cache with `pnpm prune`, some weird error starting appearing in project. The output of the error is below:
```
ENOENT: no such file or directory, copyfile '/Users/rodrigoburigo/Library/pnpm/store/v3/files/76/c03e1cf89b110798a6e406a52aa4c67b87f8af8f9bfd7dacc19bc3382768bc4fb6b9b3e9eabeddbff89a82619b5f0e15f3de87b32e85518e3ad54696643c1e-exec' -> '/Users/rodrigoburigo/Documents/Projects/etopocart-turbo/node_modules/_tmp_42601_dd18b028cc8633c25d70e22921d1f601/node_modules/@mapbox/tiny-sdf/index.d.ts'
```

Can you please help me? I don't know how to resolve this.

**Comment by mourner** [comment]
Hmm, I'm not sure — this looks like more of a pnpm issue than tinysdf. @zkochan have you seen anything like this before, any pointers maybe?

**Comment by zkochan** [comment]
I guess you can only fix it by removing the store. I have heard about this issue but couldn't repro yet.

**Comment by digoburigo** [comment]
@zkochan That's exactly it. I deleted the store folder, and reinstall without anything cached and it's starting to work again. @mourner Sorry for open this issue here! Feel free to close it. Thanks for you time and information!
