### ISSUE TITLE
Canvas2D multiple readback operations getImageData willReadFrequently

### ISSUE THREAD

**Issue by jfuehner** [mapbox/tiny-sdf#51]
I started noticing with a recent version of Chrome (v108) the below warning within the console...

Canvas2D: Multiple readback operations using getImageData are faster with willReadFrequently attribute set to true.

I am using the deck.gl framework which leverages tiny-sdf as one of its dependencies. Curious if this has been reported previously? Seems like it may be impactful to performance and has been reported to other projects (https://github.com/openlayers/openlayers/issues/14221).

Thanks!

**Comment by mourner** [comment]
This was fixe since at least v2.0: https://github.com/mapbox/tiny-sdf/commit/83bbd76b62548dcd8e1d589cbea67d278d281cf5
So the downstream projects would just need to update to a newer version of tiny-sdf.
